#!/bin/sh
set -o errexit
VERSION="$1"
cat >module.json <<EOF
{
   "name" : "lang-de-pf2e",
   "title" : "de - Pathfinder 2e",
   "version" : "$VERSION",
   "minimumCoreVersion" : "0.5.0",
   "author" : "henry4k",
   "description" : "German language support for Pathfinder 2e",
   "languages" : [
      {
         "lang" : "de",
         "name" : "German",
         "path" : "de.json"
      }
   ],
   "packs" : [],
   "scripts" : [],
   "styles": ["style.css"],
   "url" : "https://gitlab.com/henry4k/foundryvtt-pathfinder2e-lang-de",
   "manifest" : "https://gitlab.com/henry4k/foundryvtt-pathfinder2e-lang-de/-/raw/master/module.json",
   "download" : "https://gitlab.com/henry4k/foundryvtt-pathfinder2e-lang-de/-/jobs/artifacts/v$VERSION/download?job=build"
}
EOF
git add --all
git commit -m "Released version $VERSION"
git tag --force "v$VERSION"
git push --tags --force
